/**
 * @fileoverview gRPC-Web generated client stub for k3s
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.30.2
// source: proto/deployment.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.k3s = require('./deployment_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.k3s.DeploymentServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.k3s.DeploymentServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.k3s.ListRequest,
 *   !proto.k3s.ListResponse>}
 */
const methodDescriptor_DeploymentService_ListDeployments = new grpc.web.MethodDescriptor(
  '/k3s.DeploymentService/ListDeployments',
  grpc.web.MethodType.UNARY,
  proto.k3s.ListRequest,
  proto.k3s.ListResponse,
  /**
   * @param {!proto.k3s.ListRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.k3s.ListResponse.deserializeBinary
);


/**
 * @param {!proto.k3s.ListRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.k3s.ListResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.k3s.ListResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.k3s.DeploymentServiceClient.prototype.listDeployments =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/k3s.DeploymentService/ListDeployments',
      request,
      metadata || {},
      methodDescriptor_DeploymentService_ListDeployments,
      callback);
};


/**
 * @param {!proto.k3s.ListRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.k3s.ListResponse>}
 *     Promise that resolves to the response
 */
proto.k3s.DeploymentServicePromiseClient.prototype.listDeployments =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/k3s.DeploymentService/ListDeployments',
      request,
      metadata || {},
      methodDescriptor_DeploymentService_ListDeployments);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.k3s.CreateRequest,
 *   !proto.k3s.StatusResponse>}
 */
const methodDescriptor_DeploymentService_CreateDeployment = new grpc.web.MethodDescriptor(
  '/k3s.DeploymentService/CreateDeployment',
  grpc.web.MethodType.UNARY,
  proto.k3s.CreateRequest,
  proto.k3s.StatusResponse,
  /**
   * @param {!proto.k3s.CreateRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.k3s.StatusResponse.deserializeBinary
);


/**
 * @param {!proto.k3s.CreateRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.k3s.StatusResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.k3s.StatusResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.k3s.DeploymentServiceClient.prototype.createDeployment =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/k3s.DeploymentService/CreateDeployment',
      request,
      metadata || {},
      methodDescriptor_DeploymentService_CreateDeployment,
      callback);
};


/**
 * @param {!proto.k3s.CreateRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.k3s.StatusResponse>}
 *     Promise that resolves to the response
 */
proto.k3s.DeploymentServicePromiseClient.prototype.createDeployment =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/k3s.DeploymentService/CreateDeployment',
      request,
      metadata || {},
      methodDescriptor_DeploymentService_CreateDeployment);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.k3s.DeleteRequest,
 *   !proto.k3s.StatusResponse>}
 */
const methodDescriptor_DeploymentService_DeleteDeployment = new grpc.web.MethodDescriptor(
  '/k3s.DeploymentService/DeleteDeployment',
  grpc.web.MethodType.UNARY,
  proto.k3s.DeleteRequest,
  proto.k3s.StatusResponse,
  /**
   * @param {!proto.k3s.DeleteRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.k3s.StatusResponse.deserializeBinary
);


/**
 * @param {!proto.k3s.DeleteRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.k3s.StatusResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.k3s.StatusResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.k3s.DeploymentServiceClient.prototype.deleteDeployment =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/k3s.DeploymentService/DeleteDeployment',
      request,
      metadata || {},
      methodDescriptor_DeploymentService_DeleteDeployment,
      callback);
};


/**
 * @param {!proto.k3s.DeleteRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.k3s.StatusResponse>}
 *     Promise that resolves to the response
 */
proto.k3s.DeploymentServicePromiseClient.prototype.deleteDeployment =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/k3s.DeploymentService/DeleteDeployment',
      request,
      metadata || {},
      methodDescriptor_DeploymentService_DeleteDeployment);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.k3s.Empty,
 *   !proto.k3s.NamespacesResponse>}
 */
const methodDescriptor_DeploymentService_ListNamespaces = new grpc.web.MethodDescriptor(
  '/k3s.DeploymentService/ListNamespaces',
  grpc.web.MethodType.UNARY,
  proto.k3s.Empty,
  proto.k3s.NamespacesResponse,
  /**
   * @param {!proto.k3s.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.k3s.NamespacesResponse.deserializeBinary
);


/**
 * @param {!proto.k3s.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.k3s.NamespacesResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.k3s.NamespacesResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.k3s.DeploymentServiceClient.prototype.listNamespaces =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/k3s.DeploymentService/ListNamespaces',
      request,
      metadata || {},
      methodDescriptor_DeploymentService_ListNamespaces,
      callback);
};


/**
 * @param {!proto.k3s.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.k3s.NamespacesResponse>}
 *     Promise that resolves to the response
 */
proto.k3s.DeploymentServicePromiseClient.prototype.listNamespaces =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/k3s.DeploymentService/ListNamespaces',
      request,
      metadata || {},
      methodDescriptor_DeploymentService_ListNamespaces);
};


module.exports = proto.k3s;

